import { Metadata } from "next";
import Navbar from "./navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Survey",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ScrollArea className="h-screen">
      <Navbar />
      <div className="mt-28 px-10">{children}</div>
    </ScrollArea>
  );
}
